### ISSUE TITLE
AppImage won't launch on EndeavourOS (Arch based distro)

### ISSUE THREAD

**Issue by larpon** [ttytm/emoji-mart-desktop#15]
I get the following when executing the latest AppImage from releases:

```
./emoji-mart-desktop-x86_64.AppImage 
/tmp/.mount_emoji-aCPHDV/usr/bin/emoji-mart: symbol lookup error: /usr/lib/libgio-2.0.so.0: undefined symbol: g_assertion_message_cmpint
```

My initial guess is that you just need to bundle `libgio` in the AppImage as well :)

**Comment by ttytm** [comment]
Hey @Larpon 

Thanks for the report!
What DE are you using on endevour? I'm asking as it might be more than just `libgio` that's missing.

**Comment by larpon** [comment]
Hi!

I use KDE 5

**Comment by ttytm** [comment]
I run into too many when trying to get a satisfactory result for an AppImage that works across many distros.

As alternative there are now binaries available that should work independently. They are faster than the AppiIage and have less size.

I've been using KDE as my main distro for years. I think the emoji picker that comes with it is great. The AppImage doesn't work for me here either. The picker was built when I used PopOS for a few weeks - I missed a good picker for Gnome. The AppImage was then tested on Ubuntu.

But the binaries do work, and I'll classify them as good a alternative :slightly_smiling_face: .

https://github.com/ttytm/emoji-mart-desktop/releases/tag/v0.4.0
